#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# VirtualEnvsWrapper

if [[ -d "${ZDOTDIR:-$HOME}/.virtualenvs" ]]; then
    export WORKON_HOME="${ZDOTDIR:-$HOME}/.virtualenvs"
    source /usr/local/bin/virtualenvwrapper.sh
else
    mkdir -p "${ZDOTDIR:-$HOME}/.virtualenvs"
    export WORKON_HOME="${ZDOTDIR:-$HOME}/.virtualenvs"
    source /usr/local/bin/virtualenvwrapper.sh
fi

# Aliases
alias internet='ping google.ch'
alias mtrg='mtr google.ch'
alias wifi='wicd-curses'

alias clone='urxvt &'
alias ris='ristretto &'

alias such='git'
alias much='git'
alias very='git'

alias pissant='echo Mais ouais mon gars'
